# Generated by Django 5.2.8 on 2025-11-10 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('pais', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('biografia', models.TextField(blank=True)),
                ('sitio_web', models.URLField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_conexion', models.DateTimeField(auto_now=True)),
                ('privado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('portada', models.ImageField(upload_to='portadas/')),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Maculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=20)),
                ('interes', models.TextField(blank=True)),
                ('educacion', models.TextField(blank=True)),
                ('trabajo', models.TextField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
